<?php echo $this->doctype(); ?>

<html lang="en">

    <head>
        <meta charset="utf-8">


        <!-- Le styles -->
        <?php
        echo $this->headLink()
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-datepicker.css')
        ?>

        <!-- Scripts -->

        <!--<script data-require="angular.js@*" data-semver="1.2.0-rc3-nonmin" src="http://localhost/ZendSkeletonApplication/public/js/angular.js"></script>-->
        <!--<script data-require="ng-table@*" data-semver="0.3.0" src="http://localhost/ZendSkeletonApplication/public/js/ng-table.js"></script>-->

        <link data-require="ng-table@*" data-semver="0.3.0" rel="stylesheet" href="http://localhost/ZendSkeletonApplication/public/css/ng-table.css" />
        <link data-require="bootstrap-css@*" data-semver="3.0.0" rel="stylesheet" href="http://localhost/ZendSkeletonApplication/public/css/bootstrap.min.css" />
        <?php
        echo $this->headScript()->setAllowArbitraryAttributes(true)
                ->appendFile($this->basePath() . '/js/angular.js', 'text/javascript', array('data-require' => 'angular.js@*', 'data-semver' => '1.2.0-rc3-nonmin'))
                ->appendFile($this->basePath() . '/js/ng-table.js', 'text/javascript', array('data-require' => 'ng-table@*', 'data-semver' => '0.3.0'))
                ->appendFile($this->basePath() . '/js/jquery.js')
                ->appendFile($this->basePath() . '/js/bootstrap-datepicker.js')
                ->appendFile($this->basePath() . '/js/script.js')
        ;
        ?>

        <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css" />
        <script src="http://code.jquery.com/jquery-1.8.3.js"></script>
        <script src="http://code.jquery.com/ui/1.10.0/jquery-ui.js"></script>  
        <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.23/jquery-ui.js"></script>
        <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.0.4/angular.min.js"></script>

    </head> 

    <body ng-app="main">
        ajouter todo
        <?php echo $this->content; ?>
        <footer>copyright achraf</footer>
    </body>

</html>
