<form ng-submit="submit()" ng-controller="DemoCtrl">
    Enter text and hit enter:
    <input type="text" ng-model="text" name="text" />
    <!--<div class="control-group input-append">-->
<input data-provide="datepicker">
<!--<button type="button" class="btn" data-toggle="datepicker"><i class="icon-calendar"></i></button>-->
    <!--</div>-->
    <input type="submit" id="submit" value="Submit" />
    <pre>list={{list}}</pre>
</form>
<div class="control-group input-append">
    <input type="text" ng-model="datepicker.date" data-date-format="dd/mm/yyyy" bs-datepicker/>
    <button type="button" class="btn" data-toggle="datepicker"><i class="icon-calendar"></i></button>
</div>